services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 4956 # 루트 비밀번호
      MYSQL_DATABASE: dojusik      # 자동 생성할 데이터베이스
      # MYSQL_USER: root              # 사용자
      MYSQL_PASSWORD: 4956      # 사용자 비밀번호
    ports:
      - "3306:3306"  # MySQL 포트
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql  # 데이터가 유지되도록 볼륨 설정

  springboot-be:
    image: springboot-be:latest
    container_name: springboot-be
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dojusik
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 4956
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:  # MySQL 데이터 지속을 위한 볼륨 설정
